package com.bad_code.tapsey.codeonetwothree.app.view;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.SoftBevelBorder;

import com.bad_code.tapsey.codeonetwothree.app.model.factory.datatype.MyClassFactory;
import com.bad_code.tapsey.codeonetwothree.environment.view.BottomSpace;

import java.awt.FlowLayout;
import java.awt.Font;

@SuppressWarnings("serial")
public class CodePanel extends JPanel {
	JPanel panel;
	public CodePanel() {
		setBackground(new Color(102, 102, 102));
		setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		setLayout(new BorderLayout(0, 0));
		
		JPanel classes_panel = new JPanel();
		classes_panel.setBackground(new Color(102, 102, 102));
		add(classes_panel, BorderLayout.WEST);
		classes_panel.setLayout(new BoxLayout(classes_panel, BoxLayout.Y_AXIS));
		
		
		JLabel lblCodePane = new JLabel("Pachabuda chivakwa");
		lblCodePane.setToolTipText("This is pane displays the logical code generated by the user.");
		lblCodePane.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCodePane.setForeground(new Color(255, 255, 255));
		add(lblCodePane, BorderLayout.NORTH);
		
		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setViewportBorder(new SoftBevelBorder(BevelBorder.LOWERED, null, null, null, null));
		add(scrollPane, BorderLayout.CENTER);
		
		panel = new JPanel();
		panel.setForeground(Color.WHITE);
		panel.setBackground(new Color(51, 51, 51));
		panel.setLayout(new BorderLayout(5, 5));
		BottomSpace bottomSpace = new BottomSpace();
		FlowLayout flowLayout = (FlowLayout) bottomSpace.getLayout();
		flowLayout.setHgap(0);
		flowLayout.setVgap(0);
		panel.add(bottomSpace,BorderLayout.SOUTH);
		JPanel panel_1 = new JPanel();
		FlowLayout flowLayout_1 = (FlowLayout) panel_1.getLayout();
		flowLayout_1.setAlignment(FlowLayout.LEFT);
		panel_1.setBackground(new Color(51, 51, 51));
		panel.add(panel_1, BorderLayout.CENTER);
		scrollPane.setViewportView(panel);

		MyClassFactory mclsfctrNewClass = new MyClassFactory(panel_1);		
		mclsfctrNewClass.setToolTipText("click to create new class.");
		mclsfctrNewClass.setForeground(new Color(255, 255, 255));
		mclsfctrNewClass.setBackground(new Color(51, 51, 51));
		mclsfctrNewClass.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 12));
		mclsfctrNewClass.setText("Mhando idva");
		classes_panel.add(mclsfctrNewClass);
	
		
	}
	
	
	public void onStart(){
		
	}
	
	public void onStartFinnished(){
		
	}
	
	public void onStop(){
		
	}

}
