package com.bad_code.tapsey.codeonetwothree.app.view;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.SoftBevelBorder;

import com.bad_code.tapsey.codeonetwothree.app.model.factory.datatype.MyClassFactory;
import com.bad_code.tapsey.codeonetwothree.environment.view.BottomSpace;

import defaultvalues.Constants;

import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Component;
import java.awt.Dimension;

@SuppressWarnings("serial")
public class CodePanel extends JPanel {
	JPanel panel;
	public CodePanel() {
		setBackground(Color.decode(Constants.BACK_COLOR));
		setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
		setLayout(new BorderLayout(0, 0));
		
		JPanel classes_panel = new JPanel();
		classes_panel.setBackground(Color.decode(Constants.BACK_COLOR));
		add(classes_panel, BorderLayout.WEST);
		classes_panel.setLayout(new BoxLayout(classes_panel, BoxLayout.Y_AXIS));
		
		
		
		JLabel lblCodePane = new JLabel("Mando dzako");
		classes_panel.add(lblCodePane);
		lblCodePane.setToolTipText("Below will be a list of classes you have created");
		lblCodePane.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCodePane.setBackground(Color.decode(Constants.BACK_COLOR));
		lblCodePane.setForeground(new Color(255, 255, 255));
		
		
		JPanel panel_2 = new JPanel();
		panel_2.setMinimumSize(new Dimension(600, 0));
		panel_2.setBackground(Color.decode(Constants.BACK_COLOR));
		add(panel_2, BorderLayout.CENTER);
		panel_2.setLayout(new BoxLayout(panel_2, BoxLayout.Y_AXIS));
		
		JLabel label = new JLabel("Pachabuda chivakwa");
		label.setAlignmentY(Component.TOP_ALIGNMENT);
		label.setVerticalAlignment(SwingConstants.TOP);
		label.setHorizontalAlignment(SwingConstants.LEFT);
		label.setToolTipText("This is pane displays the logical code generated by the user.");
		label.setForeground(Color.WHITE);
		label.setFont(new Font("Tahoma", Font.BOLD, 12));
		label.setBackground(new Color(49, 49, 49));
		panel_2.add(label);
		
		JScrollPane scrollPane = new JScrollPane();
		panel_2.add(scrollPane);
		scrollPane.setViewportBorder(null);
		
		panel = new JPanel();
		panel.setForeground(Color.WHITE);
		panel.setBackground(Color.BLACK);
		panel.setLayout(new BorderLayout(5, 5));
		BottomSpace bottomSpace = new BottomSpace();
		FlowLayout flowLayout = (FlowLayout) bottomSpace.getLayout();
		flowLayout.setHgap(0);
		flowLayout.setVgap(0);
		panel.add(bottomSpace,BorderLayout.SOUTH);
		
		
		JPanel panel_1 = new JPanel();
		panel_1.setBackground(Color.BLACK);
		FlowLayout flowLayout_1 = (FlowLayout) panel_1.getLayout();
		flowLayout_1.setAlignment(FlowLayout.LEFT);
		panel.add(panel_1, BorderLayout.CENTER);
		scrollPane.setViewportView(panel);
		
		MyClassFactory mclsfctrNewClass = new MyClassFactory(panel_1);		
		mclsfctrNewClass.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
				
		mclsfctrNewClass.setToolTipText("click to create new class.");
		mclsfctrNewClass.setForeground(new Color(255, 255, 255));
		mclsfctrNewClass.setBackground(Color.decode(Constants.FORE_COLOR));
		mclsfctrNewClass.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 12));
		mclsfctrNewClass.setText("Mhando idva");
		classes_panel.add(mclsfctrNewClass);
		
		

		
	}
	
	
	public void onStart(){
		
	}
	
	public void onStartFinnished(){
		
	}
	
	public void onStop(){
		
	}

}
